[package]
name = "fltk-scintilla"
version = "0.1.0"
edition = "2021"

[dependencies]
fltk = "1.2.25"
fltk-sys = "1.2.25"
paste = "1"
scintilla-sys = "*"
fltk-scintilla-sys = { version = "0.1.0", path = "fltk-scintilla-sys" }